### ISSUE TITLE
glslify-pex

### ISSUE THREAD

**Issue by vorg** [stackgl/glslify#47]
Experimenting with moving [pex](http://vorg.github.io/pex) to glslify. 

Goals:
- stop copy pasting shader code
- contribute to stack-gl community / npm code that is not dependent on pex
- should run in node.js/Plask
- same code can be browserify-ied to run in the browser

I started by using bundler directly but it won't cut it as i want to run the same code in Plask/node as in the Browser. Currently I use custom glslify-pex that returns promisses that I can later handle in pex code.

```javascript
//glslify-pex
var glslify = require('glslify');
var path = require('path');
var Promise = require('bluebird');

//check for dummy object when in browserify
var isPlask = require('plask').simpleWindow ? true : false;

function glslifyPex(file, opts) {
  if (isPlask) {
    return new Promise(function(resolve, reject) {
      var workingDirectory = path.dirname(process.mainModule.filename);
      var fullFilePath = path.resolve(workingDirectory, file);
      glslify.bundle(fullFilePath, opts, function(err, src) {
        if (err) {
          reject(err);
        }
        else {
          resolve(src);
        }
      })
    })
  }
  else {
    //this actually never works as glslify module will be removed by the transform
    return glslify(file, opts);
  }
}

module.exports = glslifyPex;
```

```javascript
//Modified pex-glu/Program supporting promises
if (vertSrc && vertSrc.then && fragSrc && fragSrc.then) {
    Promise.all([vertSrc, fragSrc]).then(function(sources) {
      this.addSources(sources[0], sources[1]);
      this.ready = false;
      if (this.vertShader && this.fragShader) {
        this.link();
      }
    }.bind(this)).catch(function(e) {
      console.log(e.stack)
    })
  }
```

In pex i can now do

```javascript
var program = new Program(
    glslify(__dirname + '/PBR.vert'),
    glslify(__dirname + '/PBR.frag')
  );
```

Now the only problem is fighting with disappearing `glslify` requires that get removed during transform.

## Solution 1

Conditionally include glslify-pex in Plask
```javascript
var glslify       = require('glslify');

if (Platform.isPlask) {
  glslify = require('glslify-pex');
}
```

## Solution 2

Search and replace `glslify-pex` -> `glslify` as browserify transform
```
var glslify       = require('glslify-pex');
```

and browserify transform

```javascript
function replaceGlslifyPex(file) {
    var data = '';
    return through(write, end);

    function write (buf) { data += buf }
    function end () {
        this.queue(data.replace(/glslify-pex/g, 'glslify'));
        this.queue(null);
    }
}

b.transform(replaceGlslifyPex);
```

## Solution 3

Use [browserify-swap](https://github.com/thlorenz/browserify-swap). Haven't tried yet.

My dream is that in node, glslify just returns string synchronously.

**Comment by hughsk** [comment]
Awesome you got it working in Pex!

Regarding sync vs. async, glslify-deps needs to be async for projects such as [glslb.in](http://glslb.in/), which leaves two options for getting the same results synchronously:

* Writing a `glslify-deps-sync` to reproduce the same behaviour using sync calls. Less than ideal in terms of maintenance overhead, but might be able to be automated somehow using source transforms?
* Shelling out to `require('child_process').execSync`. This is built into Node 0.12.x, but needs to be pulled in [from npm](https://www.npmjs.com/package/exec-sync) for older versions.

I think both options will cause Pex to hang while the shaders are being built, though you'd need a whole bunch of files for it to be noticeable.

Another suggestion, which I gravitate more towards because of its simplicity, would be to add an option to the glslify transform to set the module to detect and replace. After that we could use the following configuration:

``` json
{
  "browserify": {
    "transform": [
      ["glslify", { "require": "glslify-pex" }]
    ]
  }
}
```

Which would allow us to do this in browserify and get strings in return:

``` javascript
var glslify = require('glslify-pex')

var vert = glslify('./shader.vert', {})
var frag = glslify('./shader.frag', {})
```

Do you reckon that'd work? :)

**Comment by vorg** [comment]
The second solution with configuration would work. Actually `glslify-pex` is not that much `plask/pex` specific. All it does it returns `Promise` instead of a `stream`. It could be called `glslify-promise` or `glslify-node`.

Can you explain me a bit more how browserify transforms work? Does `glslify` has to return anything at all? Isn't it a string replace in the end? Is there a way I can detect that "i'm being browserified" to avoid `if (isPlask)` check?

**Comment by hughsk** [comment]
Ah, sorry for the delay!

A general-purpose `Promise` variant sounds like the perfect solution – I've actually just gone and written one up which I'll be publishing shortly. Let me know if you'd like me to add you to the repo and/or stackgl org :)

Regarding browserify transforms, they're essentially a function which returns a [Node-core Transform stream](https://nodejs.org/api/stream.html#stream_class_stream_transform). The transform stream takes the original file contents as input, and is responsible for spitting out the modified file contents on the other end. Often browserify transforms will buffer the contents of the file and operate on the file as a string – this is necessary for using non-streaming libraries, so it happens a lot.

The mysterious part of transforms such as glslify, brfs, envify and company is to use tools such as [acorn](http://ghub.io/acorn/) and [escodegen](http://ghub.io/escodegen) to perform syntax-aware source transforms by parsing and modifying the file's JavaScript AST (as opposed to doing a simple find/replace). Fortunately [static-module](http://ghub.io/static-module) handles our case pretty well, so we don't need to deal with the AST directly here, but if you're game you can dive through that dependency tree to get some deeper insight into how that works.

In the case of the `glslify` transform, we're picking up the `glslify(filename)` statement, bundling the file accordingly and replacing that statement with a string. In the case of `glslify-promise` we can just wrap that string up in a `Promise`, but also return a Promise in Node so that they'll share exactly the same API.

You can check if you're in browserify using the `process.browser` variable, which is set to `true` in browserify but should be `undefined` in Node and Plask.

**Comment by hughsk** [comment]
Published! https://github.com/stackgl/glslify-promise :)

**Comment by vorg** [comment]
This is now also solved with https://www.npmjs.com/package/glslify-sync/
