### ISSUE TITLE
[suggestion] Change API to be more build-system agnostic.

### ISSUE THREAD

**Issue by trusktr** [stackgl/glslify#57]
For example, instead of having us do

```js
// index.js
var glslify = require('glslify')
var src = glslify('/path/to/shader.glsl')
console.log(src)
```

we should be able to write

```js
// index.js
var src = require('/path/to/shader.glsl')
console.log(src)
```

and then we can let Browserify handle that with `glslify` behind the scenes. It's also just cleaner to read. And it's easier to make it work in other build systems. And it's not vendor-locked to glslify.

**Comment by hughsk** [comment]
Sadly changing the API isn't trivial, there's a number of active projects relying on what we have currently. There's other tradeoffs to consider: there's no practical way to get the above API working in Node, for example.

The API you're referring to is only for the browserify transform – we also have a CLI, Node API and Webpack Loader (the latter uses your suggested approach, as it's more conventional to do so in that community). With more context I'm sure we can help you get glslify working with your chosen build system though :)

**Comment by trusktr** [comment]
> only for the browserify transform

That's what I'd like to have fixed. That's not the same syntax as for the glslify-loader for Webpack, which makes it harder to write platform-agnostic code.

> we can help you get glslify working with your chosen build-system though

I'd like to write one syntax for any build system. For example, if I'm writing a library (not an application), I want that library to be build-system agnostic.

> there's a number of active projects relying on what we have currently

Breaking APIs in the name of progress is fine IMHO. Change the semver version appropriately. Make note of it in the docs. Programmers are smart people. I'm sure they can adapt.

**Comment by trusktr** [comment]
Check out this file in Famous Engine: https://github.com/Famous/engine/blob/master/webgl-shaders/index.js#L27

It doesn't work in Webpack. It'd be so much nicer to rewrite it as

```js
var VertexShader = require('./VertexShader.glsl')
var FragmentShader = require('./FragmentShader.glsl')

var shaders = {
    vertex: VertexShader,
    fragment: FragmentShader
};

module.exports = shaders;
```

and for that to work in both browserify and webpack build systems.

**Comment by trusktr** [comment]
> there's no practical way to get the above API working in Node

The key here is a single syntax *for build systems*. If you want to get a shader in Node, then by all means `require('glslify')` and use the API programmatically. But for browserify and webpack (and any other build systems) we should do things the conventional way, which is requiring/importing the file that is needed, and letting the build system handle it entirely behind the scenes, with conventional module syntax:

```js
let shader = require('./path/to/shader.glsl')
```

```js
impot shader from './path/to/shader.glsl'
```

**Comment by hughsk** [comment]
I'd rather change the API for glslify-loader to match the transform's, as:

1. It's closer in line to what we have with glslify-promise and the Node API.
2. There's no way to pass in options to individual shaders when using require. *It's very important we keep this feature, so there's no way we can use your suggested API*.

The consideration of Node is actually for developing with Plask, see #8.

If you're really concerned about making your library work with any build system you should be preprocessing the file on publish, e.g. with `browserify --standalone`.

Webpack has a problem for cross-platform development in that it ignores `browserify.transform` in `package.json` files. I'm going to be writing something up to fix that soon, because it breaks a bunch of packages on npm that would otherwise work (it would fix Famous too).

**Comment by mattdesl** [comment]
I am :-1: on this change.

I really disagree with webpack's require overloading. Aside from breaking node, it muddles the meaning of the function, makes static analysis harder, couples file extensions too tightly with transforms, encourages obscure syntax like query parameters and `!` prefixes, and does not allow you to pass options as @hughsk mentioned.

A good approach for modules/libraries would be to transpile source on pre-publish. This way you aren't bundling your dependencies (as you might with webpack/browserify). A `babel-glslify` plugin could enable this.

**Comment by trusktr** [comment]
> I'd rather change the API for glslify-loader to match the transform

I can live with that. :+1: 

Does `glslify('X/foo.glsl')` resolve to the `foo.glsl` file from the `X` module?

**Comment by mattdesl** [comment]
Yup! It should behave like node require algorithm. Being used here: https://github.com/mattdesl/glsl-shader-basic/blob/master/README.md

**Comment by trusktr** [comment]
I made an issue for glslify-loader: https://github.com/stackgl/glslify-loader/issues/4

**Comment by trusktr** [comment]
@mattdesl @hughsk Does the glslify browserify transform work on source files that have an `import` statement to import glslify? f.e.

```js
import glslify from 'glslify'

glslify(...)
```

Or do we have to convert that to CommonJS syntax before it'll work with the glslify transform, so that glslify can properly get rid of the `require('glslify')` call?

**Comment by trusktr** [comment]
I still think `require('foo.glsl')` is the best syntax. It's a common way to do things. For example, [browserify-css](https://github.com/cheton/browserify-css) for css files, one of many. There's gotta be another way to satisfy the configuration requirement. Perhaps `#pragma` lines in the shaders, etc, etc. IMHO. That makes things more easily cross-build-system compatible because basically every major build system supports requiring/importing custom file types; it's normal and it's not a bad thing.

There's a way to do it, I know there is, and it'll make glslify spread to other reaches of the build-system universe. Glslify can have a smaller scope: compiling glsl files. And configuration for that can be placed in the glsl files directly, or in json files in the filesystem, etc. Shoot, you could even make it so GLSL files can import json configuration files before any code, or something, so that coponents can be augmented with configuration from users. There's lots of ways to solve this problem to make syntax simple and common for all build systems while still maintaining the Node.js API for non-build systems for those who want that.

Parsing for glslify() calls in code, IMHO, is asking for complexity because there will inevitably be some structure that we haven't accounted for. We all know require/import syntax, and it's simple and hard to mangle.

```glsl
#pragma glslify-config: { "foo":"foo", "bar": "bar" }
...
```

```glsl
#pragma glslify-config: './config.json'
...
```

So many ways to make it happen.

**Comment by trusktr** [comment]
Well, anyways, let me know about that previous `require` question. I'll have time to PR the glslify-loader repo this weekend. I don't know what staticModule does: does it also remove the matching `glslify` require call?

**Comment by mattdesl** [comment]
Regarding import -- there is a blocker in `static-module` 
https://github.com/babel/babelify/issues/81

> It's a common way to do things. For example, browserify-css for css files, one of many.

It's not really that common in browserify; Substack and plenty of others have voiced their concerns with overloading `require` statements and it's one of the reasons [static-module](https://www.npmjs.com/package/static-module) is encouraged for browserify transforms of this nature, rather than taking the `browserify-css` approach.

If you want code that works in many environments (read: node, browser) then you should petition Webpack and its users to stop require overloading in their libraries and modules. :smile: 

Keep in mind:

- `require('./foo.glsl')` does not work in Node
- `require('./foo.glsl')` does not allow you to pass an options object to the glslify parser
- `require('./foo.glsl')` tightly couples extensions to a single transform

**Comment by trusktr** [comment]
> require('./foo.glsl') does not work in Node

But it can be pre-processed in a prepublish script easily. I agree 100% on not publishing it in that form to npm (actually, I would suggest publishing the built files in the root of the package, and in the src folder leave all the files in that form, giving end users ultimate control). For example:

```js
foo.js // pre-processed
bar.js // pre-processed
src/
  foo.js // original
  bar.js // original
```

people who use node CommonJS directly can `require('packageName/foo')`, and it'll work. People who use Webpack, JSPM, etc, can use either the root files, or the src files, configurable in their build system. JSPM, for example, will take the root folder that you specify and install that at the root in the installed package. For example, if I set the root to `src`, then the installed package will look like this:

```js
foo.js // original
bar.js // original
```

and the JSPM user can decide how to handle `require('foo.glsl')` calls. If the JSPM user doesn't want to handle those, he can choose to use the package's original root. Webpack and JSPM (and browserify, but not as easily) will compile only code that's used, and leave out unused code, so the final bundle will be lean, regardless of the filestructure.

**Comment by trusktr** [comment]
> require('./foo.glsl') does not allow you to pass an options object to the glslify parser

Hence the `#pragma suggestion`.

**Comment by trusktr** [comment]
> require('./foo.glsl') tightly couples extensions to a single transform

It doesn't couple it to any transform at all. I could go and make something called `webglify` (for lack of a better name) and now that can be an alternative to `glslify` (not that I want to do that). That seems to actually give the user more options to choose from for the transform.

**Comment by trusktr** [comment]
But anyway, maybe we can get the glslify browserify transform working nicely in Webpack with [`transform-loader`](https://github.com/webpack/transform-loader), which could eliminate the need for glslify-loader altogether, and users can at least write code in a single way across Browserify and Webpack. :)

**Comment by mattdesl** [comment]
> But it can be pre-processed in a prepublish script easily. 

For this, it would need to use a *transpiler* (Babel) rather than a *bundler* (webpack, browserify). Otherwise you end up duplicating dependencies.

Regardless; there is no need to transform Node code if it already works out of the box. We are only transforming client-side because we don't have access to the file system. This is why we use `require('fs').readFileSync` in Node, and `brfs` in browserify.

Using `require('foo/src/blah')` is generally not a good idea. You don't want your users accessing the internals of your module, since they may change without an associated semantic version change.

> Hence the #pragma suggestion which I'm sure can work. I'm sure there are other ways too.

The parser/tokenizer is already running by the time it hits pragma statements:

```glsl
#version 300 es

// blah blah
#pragma glslify-options: ./options
```

> It doesn't couple it to any transform at all.

The following example shows what I mean about coupling extensions to transforms. Two transforms which both work independently in the same application, even though they use the same extension.

```js
var shader1 = require('glslify')('./foo.glsl')
var shader2 = require('webglify')('./bar.glsl')
```

In the above situation, you can no longer use `require('./foo.glsl')`, and instead need to change the syntax of the require statement.

--

Sorry, but using `require('./foo.glsl')` seems like an incredulous amount of complexity for very little gain, except for doing things "the webpack way" (which many people would say is wrong).

I would say the best solution is to have a `babel-glslify` plugin so that modules/libraries can inline shaders on pre-publish. You lose features like `glslify-optimize`, but it works in node/browserify/webpack/etc.

**Comment by trusktr** [comment]
> it would need to use a transpiler (Babel) rather than a bundler (webpack, browserify). Otherwise you end up duplicating dependencies.

Yes, of course.

> Using require('foo/src/blah') is generally not a good idea. You don't want your users accessing the internals of your module, since they may change without an associated semantic version change.

Any change that doesn't change the API of a package should always result in an increment of `patch` number. If a semantic version change hasn't happened and we've changed internals of a package, then that package isn't semantically versioned.

> The parser/tokenizer is already running by the time it hits pragma statements:

Those are implementation details, details that can be modified.

> var shader2 = require('webglify')('./bar.glsl')

`webglify` (if it ever existed) would not have an API like that. Webglify would be strictly a browserify transform with API that is not intended to be used programmatically as in that example (except for occasions where the user is hacking the browserify build system, and in that case knows what he/she is doing because that usage won't be part of the publicly documented API). Webglify would be doing it's job: being a browserify transform. As far as the webglify docs would be concerned, the usage would specify that `require('./bar.glsl')` is the syntax to use. Webglify would be a wrapper to another package that *can* be used the way you describe, in Node.js, without modification.

**Comment by yoshuawuyts** [comment]
`require('./foo.glsl')` seems silly. I think it's a very bad idea to overload `require`, regardless if webpack is already doing that or not.

@trusktr I agree with the sentiment in this thread. Feel free to build your module if you think it's a good idea. Keep in mind however that everyone in this thread is advising you against it.

**Comment by trusktr** [comment]
@hughsk @mattdesl @yoshuawuyts I've had no luck with `transform-loader` to apply `glslify` as a browserify transform in Webpack. I'm having this issue: https://github.com/webpack/webpack/issues/1373

Any ideas what might be wrong?

**Comment by yoshuawuyts** [comment]
I have no idea. Looking at the stack trace it's webpack's [custom resolver](https://github.com/webpack/enhanced-resolve) that's complaining. Maybe the webpack team can help.
