### ISSUE TITLE
#define GLSLIFY 1

### ISSUE THREAD

**Issue by vanruesc** [stackgl/glslify#59]
I've been working on the modularisation of three.js and wanted to use glslify to fully include the library's shaders in the browserified bundle.

The [ShaderLib](https://github.com/vanruesc/three.js/blob/dev/src/renderers/shaders/ShaderLib.js) of three.js concatenates multiple [ShaderChunks](https://github.com/vanruesc/three.js/blob/dev/src/renderers/shaders/ShaderChunk.js) to create the final shaders. I had to resort to fs.readFileSync and the [brfs](https://github.com/substack/brfs) transform, because glslify adds the line "#define GLSLIFY 1" to each shader file. The combined shaders then redefine that macro, of course, and fail.

@mattdesl asked me to report this here, so I prepared a little demo project to better illustrate the problem.
- [Simplified ShaderLib](https://github.com/vanruesc/glslify-issue/blob/master/src/glslify-issue.js) 
- [Simplified ShaderChunks](https://github.com/vanruesc/glslify-issue/blob/master/src/ShaderChunk.js) 
- [Some arbitrary glsl files](https://github.com/vanruesc/glslify-issue/tree/master/src/ShaderChunk)
- [The browserified bundle](https://github.com/vanruesc/glslify-issue/blob/master/build/glslify-issue.js)
- [The undesired outcome](http://vanruesc.github.io/glslify-issue/)

_Using glslify version 2.2.1_

**Comment by mattdesl** [comment]
Thanks for the report. 

glslify was designed to resolve (file) dependencies at build-time into a single shader source. It does things like descope variable names `foo` into `foo_1`, to avoid collisions. It seems like your use case is better suited for a simple `brfs` transform since you are just inlining files into the final bundle.

So, even if we remove the `#define GLSLIFY`, I suspect you'll run into other road blocks with this approach.

What you're looking for is run-time shader generation, which would be a cool feature even if only limited support is possible. Related issue:
https://github.com/stackgl/glslify/issues/58

**Comment by vanruesc** [comment]
Ok, got it! Thank you for the insight.
