### ISSUE TITLE
glslify() in doesn’t return string

### ISSUE THREAD

**Issue by timseverien** [stackgl/glslify#74]
```js
const glslify = require('glslify'); 
const src = glslify('my-shader.glsl');
```

`src` is a `DuplexWrapper`, not a string, as suggested by the docs. I can’t pipe it or use one of the events to read the source.

- npm: 3.8.0
- node: 5.6.0
- glslify: 5.0.2

**Comment by mattdesl** [comment]
The main export of `glslify` is a source transform (i.e. typically used in bundlers like browserify or webpack).

You can use [glslify-promise](https://github.com/stackgl/glslify-promise) for a consistent interface between node/browserify.

We should probably add these details to the main readme. :smile: PRs welcome.

**Comment by dfcreative** [comment]
Related #8.

[glslify-sync](https://npmjs.org/package/glslify-sync) is also a workaround.

**Comment by substack** [comment]
6.0.0 always returns a string in both node and browser environments. Closing.

**Comment by rreusser** [comment]
I think this change is the reason `ify-loader` no longer works with the glslify transform. See browserify/ify-loader#5 which, despite the name, affects usage of just the glslify transform. In short, it tries `tr.on('file', ...)` [here](https://github.com/browserify/ify-loader/blob/master/index.js#L64) when `tr` is a string. I think the fix is simple, but I'm still trying to figure out how to correctly wrap the string or figure out how to modify ify-loader to compensate for this change.
